"""empty message

Revision ID: 65454df5bb09
Revises: 
Create Date: 2022-11-16 06:55:28.926545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65454df5bb09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('closed_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=True))

    with op.batch_alter_table('open_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_order', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    with op.batch_alter_table('closed_order', schema=None) as batch_op:
        batch_op.drop_column('vendor')

    # ### end Alembic commands ###
